---
- name: Configure App
  hosts: app
  #hosts: reddit_app

  become: true
  #vars:
    #db_host: "123.123.123.123"
    #db_host: "{{ hostvars[groups['reddit_db'][0]]['networkInterfaces'][0]['networkIP'] }}"
  roles:
    - app
    - jdauphant.nginx
    
