############ Deploy ############
- name: Deploy App
  hosts: app
  #hosts: reddit_app
  #tags: deploy-tag
  tasks:
    - name: Fetch the latest version of application code
      #become_user: "{{ deploy_user }}"
      become: true
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: "/home/{{ deploy_user }}/reddit"
        version: monolith # <-- Указываем нужную ветку
      notify: restart puma

    - name: Bundle install
      bundler:
        state: present
        chdir: "/home/{{ deploy_user }}/reddit" # <-- В какой директории выполнить команду bundle

  handlers:
  - name: reload puma
    become: true
    systemd:
      name: puma
      daemon_reload: yes
      state: reloaded

  - name: restart puma
    become: true
    systemd: name=puma state=restarted
